#!/bin/bash

CR=(  155  40 34 70 106 142 178 209 202 196 )
AR=(  )

D=22
while (( $D <= 255 ))
do
    AR+=( $D )
    (( D+=36 ))
done

echo -e "\e[40m"
for C in "${AR[@]}"
do
    echo -e -n "\e[40;38;5;${C}m\t$C\t\e[39m"
    (( C+=6 ))
    echo -e -n "\e[40;38;5;${C}m\t$C\t\e[39m"
    (( C+=6 ))
    echo -e -n "\e[40;38;5;${C}m\t$C\t\e[39m"
    echo
done

echo -e "\e[40m"
for C in "${CR[@]}"
do
    echo -e "\e[40;38;5;${C}m\t$C\t\e[39m"
done